version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=tp_foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  tp-foyer-app:
    depends_on:
      - mysqldb
    image: youssef930/tp-foyer5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tp_foyer_db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": null,
          "spring.jpa.show-sql": true,
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  db:
  nexus-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  prometheus-data:
  grafana-data:
