apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
spec:
  selector:
    matchLabels:
      app: tpfoyer
  replicas: 2
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: adminaymen/tpfoyer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-ssvc
spec:
  selector:
    app: tpfoyer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8082
