version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=tp_foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  tp-foyer-app:
    depends_on:
      - mysqldb
    # build:
    #   context: .
    image: abbesachraf/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tp_foyer_db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": null,
          "spring.jpa.show-sql": true,
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    stdin_open: true
    tty: true

volumes:
  db: